In [1]:
#Importing Libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import cv2
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from tqdm import tqdm

from IPython import get_ipython
from IPython.display import display

In [3]:
#Importing Images

image_paths = [
    "./Cats/1.jpg",
    "./Dogs/10.jpg",
    "./Dogs/100.jpg",
    "./Cats/10001.jpg",
    "./Dogs/10003.jpg",
    "./Dogs/10006.jpg",
    "./Cats/10022.jpg"
]

image_labels = [
    0,  # Label for ./1.jpg
    1,  # Label for ./10.jpg
    2,  # Label for ./100.jpg
    0,  # Label for ./10001.jpg 
    1,  # Label for ./10003.jpg 
    2,  # Label for ./10006.jpg 
    0   # Label for ./10022.jpg 
]

IMG_SIZE = 64
data = []
labels = []

for i, img_path in enumerate(tqdm(image_paths)):
    try:
        img_array = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
        if img_array is not None:
            resized = cv2.resize(img_array, (IMG_SIZE, IMG_SIZE))
            data.append(resized.flatten())
            labels.append(image_labels[i])

    except Exception as e:
        print(f"Error loading image {img_path}: {e}")
        pass

data = np.array(data)
labels = np.array(labels)

print("Image loading complete.")
print(f"Number of images loaded: {len(data)}")
print(f"Number of labels loaded: {len(labels)}")

100%|███████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 192.03it/s]

Image loading complete.
Number of images loaded: 7
Number of labels loaded: 7


In [4]:
data = np.array(data)
labels = np.array(labels)

In [5]:
#Training & Testing data

X = data
y = labels
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [6]:
print("Data splitting complete.")
print(f"Training set size: {len(X_train)} samples")
print(f"Testing set size: {len(X_test)} samples")

Data splitting complete.
Training set size: 5 samples
Testing set size: 2 samples


In [7]:
#SVM Model

model = SVC(kernel='linear')

print("Training SVM model...")
model.fit(X_train, y_train)

print("SVM model training complete.")

Training SVM model...
SVM model training complete.


In [8]:
#Evaluating SVM Model

y_pred = model.predict(X_test)

In [9]:
#Calculating Accuracy

accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy on the test set: {accuracy:.4f}")

Accuracy on the test set: 0.5000


In [10]:
#Classification Report

print("\nClassification Report:")
print(classification_report(y_test, y_pred))


Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       1.00      1.00      1.00         1
           2       0.00      0.00      0.00         0

    accuracy                           0.50         2
   macro avg       0.33      0.33      0.33         2
weighted avg       0.50      0.50      0.50         2



C:\Users\Hetsh\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Hetsh\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Hetsh\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, 

In [11]:
#Confusion Matrix

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))


Confusion Matrix:
[[0 0 1]
 [0 1 0]
 [0 0 0]]
